@startuml
class org.jcat.core.stream.JCatStream {
}
abstract class org.jcat.core.input.AbstractInput {
+ String read()
+ String getEncode()
+ String setEncode(String)
+ void close()
}

class org.jcat.core.output.StandardOutput {
+ void close()
}

abstract class org.jcat.core.stream.AbstractJCatStream {
+ boolean next()
+ boolean hasNext()
+ String readLine()
+ void write(String)
+ void writeLine(String)
+ void open()
+ void close()
+ I getInput()
+ O getOutput()
+ StreamContext getContext()
}

class org.jcat.plugin.impl.ReplaceShowNonPrintingPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.core.output.FileOutput {
+ void close()
}

class org.jcat.plugin.impl.ReplaceTabsPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

interface org.jcat.plugin.IPlugin {
+ void setOption(CatOption)
+ boolean isEnabled()
}

class org.jcat.core.input.StandardInput {
+ void close()
}

class org.jcat.plugin.impl.ReplaceNumberPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.plugin.impl.ReplaceNumberNonBlankPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.plugin.PluginHolder {
+ void addReplacePlugin(IReplacePlugin[])
+ void addHelpPlugin(IHelpPlugin[])
+ void showOptions()
+ String replace(StreamContext,String)
+ boolean existsHelpPlugins()
}

class org.jcat.JCatApp {
+ void exec()
+ {static} void main(String[])
}

abstract class org.jcat.plugin.AbstractReplacePlugin {
+ String replace(StreamContext,String)
}

class org.jcat.plugin.impl.CommandVersionPlugin {
+ void show()
+ boolean isEnabled()
}

class org.jcat.plugin.impl.CommandHelpPlugin {
+ void show()
+ boolean isEnabled()
}

class org.jcat.core.input.FileInput {
+ void close()
}

interface org.jcat.plugin.IReplacePlugin {
+ String replace(StreamContext,String)
}

class org.jcat.core.CatOption {
+ void addFileList(String)
+ boolean isShowAll()
+ boolean isNumberNonBlank()
+ boolean isShowEnds()
+ boolean isNumber()
+ boolean isSqueezeBlank()
+ boolean isShowTabs()
+ boolean isIgnored()
+ boolean isShowNonPrinting()
+ boolean isShowHelp()
+ boolean isShowVersion()
+ List<String> getFileList()
}

interface org.jcat.core.input.IInput {
+ String read()
+ void close()
+ String setEncode(String)
+ String getEncode()
}

interface org.jcat.core.output.IOutput {
+ void write(byte[])
+ void close()
+ String setEncode(String)
+ String getEncode()
+ void setLineFeed(String)
+ String getLineFeed()
}

class org.jcat.plugin.impl.ReplaceEndsPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

interface org.jcat.core.stream.IJCatStream {
+ O getOutput()
+ I getInput()
+ void open()
+ void close()
+ boolean next()
+ boolean hasNext()
+ String readLine()
+ void write(String)
+ void writeLine(String)
+ StreamContext getContext()
}

abstract class org.jcat.plugin.AbstractPlugin {
+ void setOption(CatOption)
}

interface org.jcat.plugin.IHelpPlugin {
+ void show()
}

abstract class org.jcat.core.output.AbstractOutput {
+ void write(byte[])
+ void close()
+ String setEncode(String)
+ String getEncode()
+ String getLineFeed()
+ void setLineFeed(String)
}

class org.jcat.plugin.impl.ReplaceSqueezeBlankPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.core.stream.StreamContext {
+ CatOption getOption()
+ void setOption(CatOption)
+ String getLineCurrent()
+ void setLineCurrent(String)
+ String getLineNext()
+ void setLineNext(String)
+ boolean isSeekFinished()
+ void setSeekFinished(boolean)
+ long getLineNumInput()
+ void setLineNumInput(long)
+ long incrementLineNumInput()
+ long getLineNumOutput()
+ void setLineNumOutput(long)
+ long incrementLineNumOutput()
}



org.jcat.core.stream.AbstractJCatStream <|-- org.jcat.core.stream.JCatStream
org.jcat.core.input.IInput <|.. org.jcat.core.input.AbstractInput
org.jcat.core.output.FileOutput <|-- org.jcat.core.output.StandardOutput
org.jcat.core.stream.IJCatStream <|.. org.jcat.core.stream.AbstractJCatStream
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceShowNonPrintingPlugin
org.jcat.core.output.AbstractOutput <|-- org.jcat.core.output.FileOutput
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceTabsPlugin
org.jcat.core.input.FileInput <|-- org.jcat.core.input.StandardInput
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceNumberPlugin
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceNumberNonBlankPlugin
org.jcat.plugin.IReplacePlugin <|.. org.jcat.plugin.AbstractReplacePlugin
org.jcat.plugin.AbstractPlugin <|-- org.jcat.plugin.AbstractReplacePlugin
org.jcat.plugin.IHelpPlugin <|.. org.jcat.plugin.impl.CommandVersionPlugin
org.jcat.plugin.AbstractPlugin <|-- org.jcat.plugin.impl.CommandVersionPlugin
org.jcat.plugin.IHelpPlugin <|.. org.jcat.plugin.impl.CommandHelpPlugin
org.jcat.plugin.AbstractPlugin <|-- org.jcat.plugin.impl.CommandHelpPlugin
org.jcat.core.input.AbstractInput <|-- org.jcat.core.input.FileInput
org.jcat.plugin.IPlugin <|-- org.jcat.plugin.IReplacePlugin
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceEndsPlugin
java.io.Closeable <|-- org.jcat.core.stream.IJCatStream
org.jcat.plugin.IPlugin <|.. org.jcat.plugin.AbstractPlugin
org.jcat.plugin.IPlugin <|-- org.jcat.plugin.IHelpPlugin
org.jcat.core.output.IOutput <|.. org.jcat.core.output.AbstractOutput
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceSqueezeBlankPlugin
@enduml