@startuml
class org.jcat.core.stream.JCatStream {
}
abstract class org.jcat.core.input.AbstractInput {
# String encode
# BufferedReader is
+ String read()
+ String getEncode()
+ String setEncode(String)
+ void close()
}


class org.jcat.core.output.StandardOutput {
}
class org.jcat.AppTest {
+ {static} Test suite()
+ void testApp()
}

abstract class org.jcat.core.stream.AbstractJCatStream {
# I input
# O output
# StreamContext context
+ boolean next()
+ boolean hasNext()
+ String readLine()
+ void write(String)
+ void writeLine(String)
+ void open()
+ void close()
+ I getInput()
+ O getOutput()
+ StreamContext getContext()
}


class org.jcat.core.stream.GlobalContext {
+ long getLineNumOutput()
+ void setLineNumOutput(long)
+ long incrementLineNumOutput()
}

class org.jcat.plugin.impl.ReplaceShowNonPrintingPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.core.output.FileOutput {
}
class org.jcat.plugin.impl.ReplaceTabsPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

interface org.jcat.plugin.IPlugin {
+ void setOption(CatOption)
+ boolean isEnabled()
}

interface org.jcat.plugin.IUsagePlugin {
+ void usage()
}

class org.jcat.core.input.StandardInput {
}
class org.jcat.plugin.impl.UsageHelpPlugin {
+ void show()
+ boolean isEnabled()
}

class org.jcat.plugin.impl.ReplaceNumberPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.plugin.impl.ReplaceNumberNonBlankPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.plugin.PluginHolder {
# CatOption option
# Set<IReplacePlugin> replacePlugins
# Set<IUsagePlugin> usagePlugins
+ void addReplacePlugin(IReplacePlugin[])
+ void addUsagePlugin(IUsagePlugin[])
+ void usage()
+ String replace(StreamContext,String)
}


abstract class org.jcat.plugin.AbstractReplacePlugin {
+ String replace(StreamContext,String)
# {abstract}String replaceLine(StreamContext,String)
}

abstract class org.jcat.plugin.AbstractUsagePlugin {
+ void usage()
# {abstract}void show()
}

class org.jcat.JCat {
+ void exec()
+ {static} void main(String[])
}

class org.jcat.core.input.FileInput {
}
interface org.jcat.plugin.IReplacePlugin {
+ String replace(StreamContext,String)
}

class org.jcat.core.CatOption {
+ boolean isUsageEnabled()
+ List<String> getFileList()
+ void addFileList(String)
+ boolean isShowAll()
+ boolean isNumberNonBlank()
+ boolean isShowEnds()
+ boolean isNumber()
+ boolean isSqueezeBlank()
+ boolean isShowTabs()
+ boolean isIgnored()
+ boolean isShowNonPrinting()
+ boolean isShowHelp()
+ boolean isShowVersion()
}

interface org.jcat.core.input.IInput {
+ String read()
+ void close()
+ String setEncode(String)
+ String getEncode()
}

interface org.jcat.core.output.IOutput {
+ void write(byte[])
+ void close()
+ String setEncode(String)
+ String getEncode()
+ void setLineFeed(String)
+ String getLineFeed()
}

class org.jcat.plugin.impl.ReplaceEndsPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

interface org.jcat.core.stream.IJCatStream {
+ O getOutput()
+ I getInput()
+ void open()
+ void close()
+ boolean next()
+ boolean hasNext()
+ String readLine()
+ void write(String)
+ void writeLine(String)
+ StreamContext getContext()
}

abstract class org.jcat.plugin.AbstractPlugin {
# CatOption option
+ void setOption(CatOption)
}


class org.jcat.plugin.impl.UsageVersionPlugin {
+ void show()
+ boolean isEnabled()
}

abstract class org.jcat.core.output.AbstractOutput {
# String encode
# String lineFeed
# OutputStream os
+ void write(byte[])
+ void close()
+ String setEncode(String)
+ String getEncode()
+ String getLineFeed()
+ void setLineFeed(String)
}


class org.jcat.plugin.impl.ReplaceSqueezeBlankPlugin {
+ String replaceLine(StreamContext,String)
+ boolean isEnabled()
}

class org.jcat.core.stream.StreamContext {
+ CatOption getOption()
+ void setOption(CatOption)
+ String getLineCurrent()
+ void setLineCurrent(String)
+ String getLineNext()
+ void setLineNext(String)
+ boolean isSeekFinished()
+ void setSeekFinished(boolean)
+ long getLineNumInput()
+ void setLineNumInput(long)
+ long incrementLineNumInput()
+ long getLineNumOutput()
+ void setLineNumOutput(long)
+ long incrementLineNumOutput()
}



org.jcat.core.stream.AbstractJCatStream <|-- org.jcat.core.stream.JCatStream
org.jcat.core.input.IInput <|.. org.jcat.core.input.AbstractInput
org.jcat.core.output.AbstractOutput <|-- org.jcat.core.output.StandardOutput
junit.framework.TestCase <|-- org.jcat.AppTest
org.jcat.core.stream.IJCatStream <|.. org.jcat.core.stream.AbstractJCatStream
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceShowNonPrintingPlugin
org.jcat.core.output.AbstractOutput <|-- org.jcat.core.output.FileOutput
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceTabsPlugin
org.jcat.plugin.IPlugin <|-- org.jcat.plugin.IUsagePlugin
org.jcat.core.input.AbstractInput <|-- org.jcat.core.input.StandardInput
org.jcat.plugin.AbstractUsagePlugin <|-- org.jcat.plugin.impl.UsageHelpPlugin
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceNumberPlugin
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceNumberNonBlankPlugin
org.jcat.plugin.IReplacePlugin <|.. org.jcat.plugin.AbstractReplacePlugin
org.jcat.plugin.AbstractPlugin <|-- org.jcat.plugin.AbstractReplacePlugin
org.jcat.plugin.IUsagePlugin <|.. org.jcat.plugin.AbstractUsagePlugin
org.jcat.plugin.AbstractPlugin <|-- org.jcat.plugin.AbstractUsagePlugin
org.jcat.core.input.AbstractInput <|-- org.jcat.core.input.FileInput
org.jcat.plugin.IPlugin <|-- org.jcat.plugin.IReplacePlugin
java.io.Closeable <|-- org.jcat.core.input.IInput
java.io.Closeable <|-- org.jcat.core.output.IOutput
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceEndsPlugin
org.jcat.plugin.IPlugin <|.. org.jcat.plugin.AbstractPlugin
org.jcat.plugin.AbstractUsagePlugin <|-- org.jcat.plugin.impl.UsageVersionPlugin
org.jcat.core.output.IOutput <|.. org.jcat.core.output.AbstractOutput
org.jcat.plugin.AbstractReplacePlugin <|-- org.jcat.plugin.impl.ReplaceSqueezeBlankPlugin
@enduml